# Generated by Django 3.2.4 on 2021-06-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=200)),
                ('start_day', models.DateTimeField(verbose_name='data de inicio da consulta')),
                ('end_day', models.DateTimeField(verbose_name='data de termino da consulta')),
                ('max_itens', models.IntegerField(default=1000)),
                ('rank_size', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(verbose_name='data de criação do tweet')),
                ('created_by', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=280)),
                ('querie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet_crawl.querie')),
            ],
        ),
    ]
