# Generated by Django 3.2.4 on 2021-06-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='querie_id',
            new_name='querie',
        ),
    ]
