# Generated by Django 3.2.4 on 2021-06-10 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0002_rename_querie_id_tweet_querie'),
    ]

    operations = [
        migrations.AddField(
            model_name='querie',
            name='executed_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 2, 57, 6, 276313, tzinfo=utc), verbose_name='data de execução da consulta'),
        ),
    ]
