# Generated by Django 3.2.4 on 2021-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0003_querie_executed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='querie',
            name='crawled_tweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='querie',
            name='executed_on',
            field=models.DateTimeField(verbose_name='data de execução da consulta'),
        ),
        migrations.AlterField(
            model_name='querie',
            name='max_itens',
            field=models.IntegerField(default=0),
        ),
    ]
