# Generated by Django 3.2.4 on 2021-06-11 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0004_auto_20210611_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querie',
            name='end_day',
            field=models.DateField(verbose_name='data de termino da consulta'),
        ),
        migrations.AlterField(
            model_name='querie',
            name='executed_on',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 23, 24, 12, 534048, tzinfo=utc), verbose_name='data de execução da consulta'),
        ),
        migrations.AlterField(
            model_name='querie',
            name='start_day',
            field=models.DateField(verbose_name='data de inicio da consulta'),
        ),
    ]
